export const ROUTES = {
  root: '/',
  landing: '/landing',
  login: '/login',
  register: '/register',
  registerUser: '/register/user',
  superAdmin: '/super-admin',
  home: '/home',
  clinicOverview: '/clinic-overview',
  clinicBranches: '/clinic-branches',
  clinicDoctors: '/clinic-doctors',
  clinicRequests: '/clinic-requests',
  clinicVisitRequests: '/clinic-visit-requests',
  homeVisitRequestsPlan: '/home-visit-requests-plan',
  adminUsers: '/admin-users',
  branchOverview: '/branch-overview',
  branchDoctors: '/branch-doctors',
  branchRequests: '/branch-requests',
  branchHomeRequests: '/branch-home-requests',
  branchClinicVisitRequests: '/branch-clinic-visit-requests',
  branchHomeVisitRequestsPlan: '/branch-home-visit-requests-plan',
  settings: '/settings',
} as const;
